server:
  port: 8082
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            callbackUrl: ${CALLBACK_URI}
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
      hibernate.show_sql: true
    hibernate.ddl-auto: create
    generate-ddl: true
  datasource:
    platform: postgres
#    url: ${DB_URL}
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
    initialization-mode: always
    initialize: true
    continue-on-error: true